### ISSUE TITLE
option --use-feature: invalid choice: 'in-tree-build' (choose from '2020-resolver', 'fast-deps')

### ISSUE THREAD

**Issue by kravrolens** [Kai-46/ARF-svox2#10]
As described in `create_env.sh`, we use conda to create envs, 
When I ran `pip install . --upgrade --use-feature=in-tree-build`, it prints:

> Usage:   
>   pip install [options] <requirement specifier> [package-index-options] ...
>   pip install [options] -r <requirements file> [package-index-options] ...
>   pip install [options] [-e] <vcs project url> ...
>   pip install [options] [-e] <local project path> ...
>   pip install [options] <archive url/path> ...
>   option --use-feature: invalid choice: 'in-tree-build' (choose from '2020-resolver', 'fast-deps')

Then ran with `pip install . --upgrade --use-feature=2020-resolver'`, it turns out:

> WARNING: --use-feature=2020-resolver no longer has any effect, since it is now the default dependency resolver in pip. This will become an error in pip 21.0.
>  Preparing metadata (setup.py) ... done
> Building wheels for collected packages: svox2
>   Building wheel for svox2 (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [18 lines of output]
> 
> ...
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for svox2
>   Running setup.py clean for svox2
> Failed to build svox2
> Installing collected packages: svox2
>   Running setup.py install for svox2 ... error
>   error: subprocess-exited-with-error
>   
>   × Running setup.py install for svox2 did not run successfully.
>   │ exit code: 1
>   ╰─> [31 lines of output]
> 
> ......
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: legacy-install-failure
> 
> × Encountered error while trying to install package.
> ╰─> svox2
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for output from the failure.

Many THX!

**Comment by m-mousatat** [comment]
how did you fix this error?
