### ISSUE TITLE
UserWarning: CUDA extension svox2.csrc could not be loaded! and AssertionError: must specify a initial checkpoint

### ISSUE THREAD

**Issue by PaiDii** [Kai-46/ARF-svox2#19]
**I encounter the following warning while running, which lead to subsequent Errors. How can I solve these？
I cancelled import svox in svox2.py, but still reported this warning.**

**warning:**
/opt/svox2/utils.py:39: UserWarning: CUDA extension svox2.csrc could not be loaded! Operations will be slow.
Please do not import svox in the svox2 source directory.
  warn("CUDA extension svox2.csrc could not be loaded! " 

**subsequent error 1:**
 Selecting random rays
Eval step
  0%|                                                                                                                                                                                | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "opt.py", line 471, in <module>
    eval_step()
  File "opt.py", line 406, in eval_step
    rgb_pred_test = grid.volume_render_image(cam, use_kernel=True)
  File "/opt/svox2/svox2.py", line 1210, in volume_render_image
    and imrend_fn_name in _C.__dict__
AttributeError: 'NoneType' object has no attribute '\_\_dict\_\_'

**subsequent error 2:**
Traceback (most recent call last):
  File "opt_style.py", line 439, in <module>
    assert os.path.isfile(args.init_ckpt), "must specify a initial checkpoint"
AssertionError: must specify a initial checkpoint

**subsequent error 3:**
Traceback (most recent call last):
  File "render_imgs.py", line 114, in <module>
    grid = svox2.SparseGrid.load(args.ckpt, device=device)
  File "/opt/svox2/svox2.py", line 1645, in load
    z = np.load(path)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt_arf/llff/fern_14.jpg/ckpt.npz/ckpt.npz'

_If you could provide some suggestions, I would greatly appreciate it!_

**Comment by mushui-ty** [comment]
i meet the same error too, could you tell me how to solve it, thanks!

**Comment by Cola-1** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt_arf/llff/fern_14.jpg/ckpt.npz/ckpt.npz'
i meet the same error too
