### ISSUE TITLE
Using my own dataset

### ISSUE THREAD

**Issue by LiquidAmmonia** [Kai-46/ARF-svox2#7]
Hi there, I have been trying to use your work on my own dataset, I managed to get the colmap results and finished the voxel optimization process. However, I come across "AttributeError: 'NSVFDataset' object has no attribute 'render_c2w'" Error when rendering results using render_imgs.py. It seemed that the code automatically identify my dataset as a 'NSVFDataset' instead of a 'LLFFDataset'. Could you tell me how to solve this bug?

My dataset looks like this after the dataset generation process provided in svox2.
![image](https://user-images.githubusercontent.com/35828555/185608244-c2b1716c-a0d9-411b-b469-83d8a1e29be3.png)

**Comment by LiquidAmmonia** [comment]
This bug only occurs when using "--render_path" argument. The testing with metrics works fine.

**Comment by Kai-46** [comment]
Did you use this `try_llff.sh` script: https://github.com/Kai-46/ARF-svox2/blob/22baf6e000e519b21ca26308f8ead1f4d2675cf5/opt/try_llff.sh#L4?

**Comment by LiquidAmmonia** [comment]
I did, but the custom dataset does not have 'pose_bounds.npy', so the dataset is extended to NSVF Dataset according to opt/util/dataset.py

**Comment by Kai-46** [comment]
You can use this script to generate the `pose_bounds.npy` file, I think: https://github.com/Fyusion/LLFF/blob/master/imgs2poses.py
