### ISSUE TITLE
Cuda out of memory after a few epochs

### ISSUE THREAD

**Issue by LiquidAmmonia** [Kai-46/ARF-svox2#8]
Hi, I have encontered CUDA out of memory after a few successful epochs, could you tell me how to solve this? 

INFO:
my command line: bash try_tnt.sh Playground 1
my GPU: a Nvidia Titan RTX with 24G Memory

Bug snapshot: 
![Snipaste_2022-08-26_18-37-25](https://user-images.githubusercontent.com/35828555/186886179-a3614878-454d-44c3-bbec-7f8937b4b698.png)

Thank you in advance for you help!

**Comment by LiquidAmmonia** [comment]
P.S. this out of memory occured in the opt_style step of the whole try_xxx.sh script, the original svox2 optimization worked fine.

**Comment by LiquidAmmonia** [comment]
P. S. This bug occured in the svox2 optimization process

**Comment by Kai-46** [comment]
You might want to check the issues in the svox2 codebase for resolving this issue.

**Comment by kravrolens** [comment]
encountered the same problem, how did you solve this problem?  thanks in advance!

**Comment by Kai-46** [comment]
You could reduce the max spatial resolution in the config file for the photorealistic radiance fields reconstruction.

**Comment by kravrolens** [comment]
> 

Thank you for your reply! i adjusted the hyper-params in `custom.json`, removed 512 resolution option in `--reso`, changed 1024 to 512 in `--background_reso`, no memory explosion occurred. But the rendering result only contains a part of the scene. don't know how to solve it, many thanks in advance!
